#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 15 15:06:19 2018

@author: u1490431
"""

# can import this as it is in the same folder as this script 
from AllFunctions import *
'''
Plots for MMiN18 poster  DISTRACTION FIGURES ONLY 

Figure 1
2
3
4
5
6


'''